export const shipsForBot = [
  [
    {
      position: {
        x: 2,
        y: 8,
      },
      direction: false,
      type: "huge",
      length: 4,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 3,
        y: 0,
      },
      direction: true,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 5,
      },
      direction: true,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 3,
        y: 5,
      },
      direction: false,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 6,
        y: 1,
      },
      direction: true,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 3,
      },
      direction: false,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 8,
        y: 2,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 6,
      },
      direction: false,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 1,
        y: 0,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 9,
      },
      direction: false,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
  ],
  [
    {
      position: {
        x: 2,
        y: 6,
      },
      direction: false,
      type: "huge",
      length: 4,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 1,
      },
      direction: true,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 5,
      },
      direction: false,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 7,
      },
      direction: true,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 1,
        y: 2,
      },
      direction: true,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 3,
        y: 3,
      },
      direction: false,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 6,
      },
      direction: false,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 2,
        y: 0,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 0,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 1,
        y: 8,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
  ],
  [
    {
      position: {
        x: 3,
        y: 0,
      },
      direction: true,
      type: "huge",
      length: 4,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 6,
        y: 2,
      },
      direction: true,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 6,
      },
      direction: false,
      type: "large",
      length: 3,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 6,
      },
      direction: true,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 2,
        y: 8,
      },
      direction: true,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 0,
        y: 2,
      },
      direction: false,
      type: "medium",
      length: 2,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 8,
        y: 0,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 7,
        y: 9,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 8,
        y: 2,
      },
      direction: true,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
    {
      position: {
        x: 4,
        y: 5,
      },
      direction: false,
      type: "small",
      length: 1,
      alive: true,
      hits: 0,
    },
  ],
];
